Update build_conda.yml

diff --git a/.github/workflows/build_conda.yml b/.github/workflows/build_conda.yml
--- a/.github/workflows/build_conda.yml
+++ b/.github/workflows/build_conda.yml
@@ -11,12 +11,26 @@ jobs:
     steps:
     - name: Checkout Files
       uses: actions/checkout@v4
+    - name: Get Version from Git Tag
+      run: |
+        # Capture the output of the git command and store in a variable
+        version=$(git describe --abbrev=0 --tags 2> /dev/null)
+        # Check if the command was successful (exit code 0)
+        if [[ $? -eq 0 ]]; then
+          echo "Version retrieved from git tag: $version"
+          # Export the version as an environment variable
+          export CONDA_PACKAGE_VERSION=$version
+        else
+          echo "Error: Could not retrieve version from git tag."
+          # Exit the workflow with an error code (optional)
+          exit 1
+        fi 
     - name: Run Docker to Build
       run: |
         conda config --append channels conda-forge
         conda config --append channels noaa-gfdl
         conda install conda-build conda-verify
-        conda build .
+        conda build --version ${{ env.CONDA_PACKAGE_VERSION }} .
     - name: Pylint All Code
       continue-on-error: true
       run: |
