edit workflows to only build doc for this branch on my fork

diff --git a/.github/workflows/create_test_conda_env.yml b/.github/workflows/create_test_conda_env.yml
--- a/.github/workflows/create_test_conda_env.yml
+++ b/.github/workflows/create_test_conda_env.yml
@@ -16,63 +16,52 @@ jobs:
         run: |
           # $CONDA is an env var pointing to root of miniconda dir
           echo $CONDA/bin >> $GITHUB_PATH
-          # info #1
-          echo "----------------------------------------------------------------"
-          ls ~
-          pwd
-          # info # 2
-          echo "----------------------------------------------------------------"
-          mkdir ~/cylc-src
-          git clone https://github.com/noaa-gfdl/fre-workflows.git ~/cylc-src/FOO__BAR__BAZ
-          ls ~/cylc-src/FOO__BAR__BAZ
-          # done 
-          echo "----------------------------------------------------------------"
           
-      - name: Create fre-cli environment
-        run: |
-          # create environment containing all dependencies
-          # the env cannot be explicitly activated in github CI/CD
-          conda env create -f environment.yml --name fre-cli
+#      - name: Create fre-cli environment
+#        run: |
+#          # create environment containing all dependencies
+#          # the env cannot be explicitly activated in github CI/CD
+#          conda env create -f environment.yml --name fre-cli
+#
+#          # add conda env's executables to github's PATH equiv.
+#          echo $CONDA/envs/fre-cli/bin >> $GITHUB_PATH
+#          
+#          # use *conda environment's pip* to install fre-cli
+#          # called w/ full path to conda's python for explicitness
+#          # called as a module (-m pip) for explicitness
+#          $CONDA/envs/fre-cli/bin/python -m pip install --prefix $CONDA/envs/fre-cli .      
+#
+#      - name: Run pytest in fre-cli environment
+#        run: |
+#          # try to make sure the right things are in GITHUB_PATH
+#          echo $CONDA/envs/fre-cli/bin >> $GITHUB_PATH
+#          
+#          # are we talking to the right python?
+#          which python
+#          python --version
+#          $CONDA/envs/fre-cli/bin/python --version
+#          
+#          # run pytest
+#          pytest --junit-xml=pytest_results.xml --config-file=fre/pytest.ini --cov-config=fre/coveragerc --cov-report=xml --cov=fre fre/
+#          
+#          # install genbadge to generate coverage badge based on xml
+#          pip install genbadge
+#          genbadge coverage -v -i coverage.xml -o docs/cov_badge.svg
+#          genbadge tests -v -i pytest_results.xml -o docs/pytest_badge.svg
+#        
+#      - name: Run pylint in fre-cli environment
+#        run: |
+#          # try to make sure the right things are in GITHUB_PATH
+#          echo $CONDA/envs/fre-cli/bin >> $GITHUB_PATH
+#
+#          # are we talking to the right python?
+#          which python
+#          python --version
+#          $CONDA/envs/fre-cli/bin/python --version
+#          
+#          # run pylint, ignored modules avoid warnings arising from code internal to those modules 
+#          pylint --max-args 6 -ry --ignored-modules netCDF4,cmor fre/ || echo "pylint returned non-zero exit code. preventing workflow from dying with this echo."
 
-          # add conda env's executables to github's PATH equiv.
-          echo $CONDA/envs/fre-cli/bin >> $GITHUB_PATH
-          
-          # use *conda environment's pip* to install fre-cli
-          # called w/ full path to conda's python for explicitness
-          # called as a module (-m pip) for explicitness
-          $CONDA/envs/fre-cli/bin/python -m pip install --prefix $CONDA/envs/fre-cli .      
-
-      - name: Run pytest in fre-cli environment
-        run: |
-          # try to make sure the right things are in GITHUB_PATH
-          echo $CONDA/envs/fre-cli/bin >> $GITHUB_PATH
-          
-          # are we talking to the right python?
-          which python
-          python --version
-          $CONDA/envs/fre-cli/bin/python --version
-          
-          # run pytest
-          pytest --junit-xml=pytest_results.xml --config-file=fre/pytest.ini --cov-config=fre/coveragerc --cov-report=xml --cov=fre fre/
-          
-          # install genbadge to generate coverage badge based on xml
-          pip install genbadge
-          genbadge coverage -v -i coverage.xml -o docs/cov_badge.svg
-          genbadge tests -v -i pytest_results.xml -o docs/pytest_badge.svg
-        
-      - name: Run pylint in fre-cli environment
-        run: |
-          # try to make sure the right things are in GITHUB_PATH
-          echo $CONDA/envs/fre-cli/bin >> $GITHUB_PATH
-
-          # are we talking to the right python?
-          which python
-          python --version
-          $CONDA/envs/fre-cli/bin/python --version
-          
-          # run pylint, ignored modules avoid warnings arising from code internal to those modules 
-          pylint --max-args 6 -ry --ignored-modules netCDF4,cmor fre/ || echo "pylint returned non-zero exit code. preventing workflow from dying with this echo."
-      
       - name: Install Sphinx and Build Documentation
         run: |
           pip install sphinx renku-sphinx-theme sphinx-rtd-theme          
@@ -82,7 +71,8 @@ jobs:
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
-        if: ${{ github.ref == 'refs/heads/main' }}
+        if: ${{ github.ref == 'refs/heads/update-fre-cmor-doc' }}
+#        if: ${{ github.ref == 'refs/heads/main' }
         with:
           publish_branch: gh-pages
           github_token: ${{ secrets.GITHUB_TOKEN }}
