Just working on docs

diff --git a/.github/workflows/create_test_conda_env.yml b/.github/workflows/create_test_conda_env.yml
--- a/.github/workflows/create_test_conda_env.yml
+++ b/.github/workflows/create_test_conda_env.yml
@@ -32,36 +32,36 @@ jobs:
           ## called as a module (-m pip) for explicitness
           $CONDA/envs/fre-cli/bin/python -m pip install --prefix $CONDA/envs/fre-cli .
 
-      - name: Run pytest in fre-cli environment
-        run: |
-          # try to make sure the right things are in GITHUB_PATH
-          echo $CONDA/envs/fre-cli/bin >> $GITHUB_PATH
-          
-          # are we talking to the right python?
-          which python
-          python --version
-          $CONDA/envs/fre-cli/bin/python --version
-          
-          # run pytest
-          pytest --junit-xml=pytest_results.xml --config-file=fre/pytest.ini --cov-config=fre/coveragerc --cov-report=xml --cov=fre fre/
-          
-          # install genbadge to generate coverage badge based on xml
-          pip install genbadge
-          genbadge coverage -v -i coverage.xml -o docs/cov_badge.svg
-          genbadge tests -v -i pytest_results.xml -o docs/pytest_badge.svg
-        
-      - name: Run pylint in fre-cli environment
-        run: |
-          # try to make sure the right things are in GITHUB_PATH
-          echo $CONDA/envs/fre-cli/bin >> $GITHUB_PATH
-
-          # are we talking to the right python?
-          which python
-          python --version
-          $CONDA/envs/fre-cli/bin/python --version
-          
-          # run pylint, ignored modules avoid warnings arising from code internal to those modules 
-          pylint --max-args 6 -ry --ignored-modules netCDF4,cmor fre/ || echo "pylint returned non-zero exit code. preventing workflow from dying with this echo."
+#      - name: Run pytest in fre-cli environment
+#        run: |
+#          # try to make sure the right things are in GITHUB_PATH
+#          echo $CONDA/envs/fre-cli/bin >> $GITHUB_PATH
+#          
+#          # are we talking to the right python?
+#          which python
+#          python --version
+#          $CONDA/envs/fre-cli/bin/python --version
+#          
+#          # run pytest
+#          pytest --junit-xml=pytest_results.xml --config-file=fre/pytest.ini --cov-config=fre/coveragerc --cov-report=xml --cov=fre fre/
+#          
+#          # install genbadge to generate coverage badge based on xml
+#          pip install genbadge
+#          genbadge coverage -v -i coverage.xml -o docs/cov_badge.svg
+#          genbadge tests -v -i pytest_results.xml -o docs/pytest_badge.svg
+#        
+#      - name: Run pylint in fre-cli environment
+#        run: |
+#          # try to make sure the right things are in GITHUB_PATH
+#          echo $CONDA/envs/fre-cli/bin >> $GITHUB_PATH
+#
+#          # are we talking to the right python?
+#          which python
+#          python --version
+#          $CONDA/envs/fre-cli/bin/python --version
+#          
+#          # run pylint, ignored modules avoid warnings arising from code internal to those modules 
+#          pylint --max-args 6 -ry --ignored-modules netCDF4,cmor fre/ || echo "pylint returned non-zero exit code. preventing workflow from dying with this echo."
 
       - name: Install Sphinx and Build Documentation
         run: |
